### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by minzhu1uts**
visulisation of the linear fit line of vix and asx200 increase

a visualisation of linear regression fit line is added into asx200 increase vs. vix increase

### CODE REVIEW

**Review by yun-s-oh — APPROVED** [review]

**Comment by ppiiesle3y** [comment]
Thanks min. could you please work with Priya to add the vix table in ERD?

**Comment by CynthiaYZ** [comment]
Thanks min. The linear regression line looks great!

**Comment by James-8212913** [comment]
Thanks Min, the negative relationship between the VIX and the ASX is interesting.

**Review by ppiiesle3y — APPROVED** [review]
Approved.

**Comment by ppiiesle3y** [comment]
this can be closed now

**Pull request closed without merging**
