### PR TITLE
Update the final version of code. 

### PR DESCRIPTION
**Pull request by CynthiaYZ**
### Completes ASX 200 Index and Housing commitment code

--------------
This is the final version of the my part of code which is ready for submission.

Changes:
Irrelevant part are removed.
Linear regression plots are added.
Brief explanations are added/updated for each plot.

### CODE REVIEW

**Comment by ppiiesle3y** [comment]
Thanks Cynthia. Could you please also add this in our final report?

**Comment by James-8212913** [comment]
Thanks Cynthia, the visuals look great. Given the ASX has demonstrated seasonal attributes I wonder if the housing commitments demonstrate similar seasonal attributes.

**Comment by minzhu1uts** [comment]
Thanks Cynthia, linear regression plots look great.

**Comment by CynthiaYZ** [comment]
> Thanks Cynthia, the visuals look great. Given the ASX has demonstrated seasonal attributes I wonder if the housing commitments demonstrate similar seasonal attributes.

This is an very interesting point of view. I will dig into it in my new project. Saying that, I don't think most of the attributes of housing commitment are seasonal. The mortgage market is significantly impacted by factors like lending policies, foreign investors (who could cause dramatic changes to the property market) policies etc. These factors all have long term influences rather than short term or seasonal.

**Review by ppiiesle3y — APPROVED** [review]
approved

**Pull request merged**
